# Generated by Django 2.2.7 on 2019-11-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='followers',
            new_name='follows',
        ),
    ]
