# Generated by Django 2.2.7 on 2019-11-22 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.CharField(default='add tweet here...', max_length=140),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('notification_total', models.IntegerField(default=0)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterclone.Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='twitterclone.TwitterUser')),
            ],
        ),
    ]
