# Generated by Django 2.2.7 on 2019-11-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_auto_20191122_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_cool',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(default='', max_length=140),
        ),
    ]
