# Generated by Django 2.2.7 on 2019-11-22 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_auto_20191122_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
