# Generated by Django 2.2.7 on 2019-11-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0005_auto_20191122_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='follow', to='twitterclone.TwitterUser'),
        ),
    ]
